### ISSUE TITLE
Android App is getting crashed when tried to call connect

### ISSUE THREAD

**Issue by lokeshsuhas** [justphil/nephila-websocket-client#1]
Hello,

Tried to call the connect from the activity, after calling the connect the app gets crashed. The same way works fine for the WebSocketClient.. I use ngrok to forward my port through url. Any idea

**Comment by scimbe** [comment]
Crash is vague symptom :-).
Have u some more details, like the function stack....
Every hint can be helpful.

**Comment by lokeshsuhas** [comment]
Got it fixed.

if (android.os.Build.VERSION.SDK_INT > 9) {
            StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
            StrictMode.setThreadPolicy(policy);
        }

by adding this line.. It was a network os exception..

**Comment by scimbe** [comment]
It would be great if u send a push request...

Thanks a lot for your feedback

**Comment by lokeshsuhas** [comment]
Its not related to the change in code, we have to add that at the activity level to handle that issue. We can put under troubleshooting in project readme file

**Comment by lokeshsuhas** [comment]
Do we have any method like canconnect to the ws uri ?
